
# Site settings
title: 孙超
name: 孙超
email: chaos@mail.ustc.edu.cn
url: "https://chaosun002.github.io/"
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "孙超"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag




